import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create" />
        <meta name="viewport" content="width=device-width, intial-scale-1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main className={`${styles.main} ${inter.className}`}>
        <h2>Hello</h2>
      </main>
    </>
  );
}
